---

- name: Check Ruby Version
  shell: ruby -v
  ignore_errors: yes
  register: rubyv

- name: Install requirements for Ruby
  apt: name={{ item }} state=installed
  with_items:
    - gcc
    - ruby2.0
    - ruby2.0-dev
    - rubygems-integration
  when: rubyv|failed
